# Generated by Django 5.0.2 on 2024-02-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_post_comments_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_list',
        ),
    ]
