# Generated by Django 5.0.2 on 2024-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_post_comment_text_comment_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_list',
            field=models.ManyToManyField(related_name='posts', to='blog.comment'),
        ),
    ]
